# Generated by Django 5.2.6 on 2025-10-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deliveryperson',
            fields=[
                ('delivery_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number_of_orders', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DeliveryPerson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('dessert_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sugar_free', models.BooleanField(blank=True, null=True)),
                ('gluten_free', models.BooleanField(blank=True, null=True)),
                ('milk_free', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dessert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discountcode',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_code', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_value', models.IntegerField()),
                ('discount_type', models.CharField(max_length=7)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DiscountCode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discountredemption',
            fields=[
                ('redemption_id', models.AutoField(primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DiscountRedemption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('milk_free', models.BooleanField(blank=True, null=True)),
                ('sugar_free', models.BooleanField(blank=True, null=True)),
                ('volume_ml', models.IntegerField(blank=True, null=True)),
                ('is_alcoholic', models.BooleanField(blank=True, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Drink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vegan', models.BooleanField(blank=True, null=True)),
                ('vegetarian', models.BooleanField(blank=True, null=True)),
                ('allergen', models.BooleanField(blank=True, null=True)),
                ('allergen_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menuitems',
            fields=[
                ('menu_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_type', models.CharField(max_length=7)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MenuItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_postal_code', models.CharField(max_length=12)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_quantity', models.IntegerField(blank=True, null=True)),
                ('drink_quantity', models.IntegerField(blank=True, null=True)),
                ('dessert_quantity', models.IntegerField(blank=True, null=True)),
                ('item_current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OrderItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=6)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('payment_timestamp', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=3)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_vegetarian', models.BooleanField(blank=True, null=True)),
                ('is_vegan', models.BooleanField(blank=True, null=True)),
                ('is_gluten_free', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pizza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PizzaIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pizza_Ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pizzapriceview',
            fields=[
                ('pizza_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=3)),
                ('ingredients_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_no_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_with_vat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PizzaPriceView',
                'managed': False,
            },
        ),
    ]
